[package]
name = "moon-assistant"
version = "0.1.0"
authors = ["kege.studios <kege.studios@gmail.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
